### ISSUE TITLE
support for color selection

### ISSUE THREAD

**Issue by JurikRistjouw** [giejay/domoticz-gbridge-plugin#11]
Is there any development going on for this new feature? https://github.com/kservices/gBridge/commit/5eae2fa632c85115f3afd5674fe04d0074fe68e5

Thanx

**Comment by giejay** [comment]
I have contacted Peter for updating the Docker images so I can start developing it:)

**Comment by JurikRistjouw** [comment]
That is very nice to read. I am eager to try it out! I will wait patiently

**Comment by giejay** [comment]
Btw, would it be enough to only have this trait available for Dimmers? Or do you have other types of devices for which the colour can also be set?

**Comment by JurikRistjouw** [comment]
No, i guess dimmers will do fine. I don't know of a colour changing device which cannot dim also.

**Comment by giejay** [comment]
I have added color support for Dimmers. You might need to remove the device and run the sync again. Or manually add the colorsettingrgb trait with topic: gBridge/u1/{domoticz_id}/colorsettingrgb

**Comment by SylvainPer** [comment]
Are the docker images ok for you ? I'm using the arm32v6 version and after the pull, the content seems the same and the new trait is not available.

**Comment by giejay** [comment]
You have to run the migration step, exec into the php-fpm docker container and execute: php artisan migrate.

**Comment by SylvainPer** [comment]
Done but nothing to migrate, I think it's more like the content of the container wasn't updated.
I looked inside and the file are still the previous ones.

**Comment by SylvainPer** [comment]
Done but nothing to migrate, I think it's more like the content of the container wasn't updated.
I looked inside and the file are still the previous ones.

**Comment by giejay** [comment]
How old are the docker images? Mine are updated last Monday

**Comment by giejay** [comment]
How old are the docker images? Mine are updated last Monday

**Comment by giejay** [comment]
Are you seeing this file: https://github.com/kservices/gBridge/blob/master/web/database/migrations/2019_03_24_095707_add_colorsetting_trait_type.php

**Comment by SylvainPer** [comment]
No, I asked Peter why.

**Comment by SylvainPer** [comment]
The problem was coming from the volume shared between the containers. The www sources wasn't updated inside, I don't know at witch moment this should happen but by removing it, I forced it.

**Comment by giejay** [comment]
You removed the volume mapping inside the yml file? I dont have the volume mapping anymore and that seems to work fine.

**Comment by SylvainPer** [comment]
I removed the existing volume, it's still in the yml file but had to recreate it on the up request.
Maybe I should remove the volume if the share between web & web-fpm is not necessary.

**Comment by giejay** [comment]
Fixed in latest commit

**Comment by SylvainPer** [comment]
Could you add bcfa695d38ce07690686db002d55f79650fc1d80 into master ?

**Comment by JurikRistjouw** [comment]
nice, i will get it asap! and test it out! Thanx for this feature @giejay

**Comment by JurikRistjouw** [comment]
how exactly do i ask for a color for a device?

**Comment by giejay** [comment]
I thought I knew, but its not working for me anymore. Also dont think its that interesting, for Google to tell me what the color of light I can just see:)

**Comment by JurikRistjouw** [comment]
Nice, google at its best i guess. Took them 3 months to fix the streaming issue.....

on topic: I also did not find any documentation on the matter from gbridge...

**Comment by giejay** [comment]
> Could you add [bcfa695](https://github.com/giejay/domoticz-gbridge-plugin/commit/bcfa695d38ce07690686db002d55f79650fc1d80) into master ?

Yes, done

**Comment by SylvainPer** [comment]
> Yes, done

Thanks !
