### ISSUE TITLE
Group support

### ISSUE THREAD

**Issue by remcom** [giejay/domoticz-gbridge-plugin#12]
Is there a way to use groups currently? A group is now set as a scene. It would be nice if groups can be controlled as a light. So that it in GH shows up as a switch and that it controls a group in domoticz.

**Comment by giejay** [comment]
Hi, 

When I add a group in Domoticz to gBridge, for me it comes up as a switch (scene) in Google Home app. Is that not what you want? You can turn off the entire group and turn it back on
