### ISSUE TITLE
Domoticz crashes at startup after updating OS, disabling gbrigde solved the crash.

### ISSUE THREAD

**Issue by JurikRistjouw** [giejay/domoticz-gbridge-plugin#14]
Not sure how to reference a cross repo issue, but here it is... 

https://github.com/domoticz/domoticz/issues/3377

If I have to elaborate, please say so. 

Kind regards,

Jurik

**Comment by giejay** [comment]
Do you know what the version of your OpenSSL install is?

**Comment by JurikRistjouw** [comment]
pi@xxxx:~ $ openssl version
OpenSSL 1.1.0k  28 May 2019

**Comment by giejay** [comment]
I'm running 1.1.0f. Could you try downgrading? Or run it in docker?

**Comment by JurikRistjouw** [comment]
not sure how to downgrade.. i would try if I knew how... But then again, it wouldn't solve the problem i guess? But willing to try. Not sure how to run it in docker at this point.

sudo pip install 'openssl==1.1.0f' --force-reinstall 

something like that?

**Comment by giejay** [comment]
I don't think you should use pip, that's for python dependencies. Apt-get install should do the trick.

**Comment by JurikRistjouw** [comment]
I'm not sure how to downgrade then... any ideas?

**Comment by giejay** [comment]
https://askubuntu.com/questions/1059801/how-to-properly-downgrade-openssl-version-under-ubuntu-18-04?rq=1

**Comment by JurikRistjouw** [comment]
I think I get the procedure, but i'm not sure about the exact version to dial in.. Could you give the exact oneliner to downgrade?

**Comment by giejay** [comment]
I dont know your exact distro so I cant give you the exact command. The version should be 1.1.0f so something like: sudo apt-get install -y --allow-downgrades openssl1.1=1.1.0f

**Comment by JurikRistjouw** [comment]
Latest update on os and beta from domoticz 11010 solved the issue.

**Comment by giejay** [comment]
Great! Thanks for the feedback
