### ISSUE TITLE
 failed to load 'plugin.py'

### ISSUE THREAD

**Issue by sailmich** [giejay/domoticz-gbridge-plugin#15]
Hello, I have two Rpi3 with zStick and raspberry running.
One has domoticz newest beta V4.10988 and  the other V4.10954 running.
I think I did the installation in the way as described in  https://doc.gbridge.io/integration/domoticz.html.
In both logs of domoticz I got the same error.
Error: (gBridge) failed to load 'plugin.py', Python Path used was '/home/pi/domoticz/plugins/domoticz-gbridge-plugin/:/usr/lib/python3.4/:/usr/lib/python3.4/plat-arm-linux-gnueabihf:/usr/lib/python3.4/lib-dynload:/usr/local/lib/python3.4/dist-packages:/usr/lib/python3/dist-packages:/usr/lib/python3.4/dist-packages:/usr/lib/dist-python'.
2019-07-12 17:51:05.002 Error: (gBridge-Steinel) Module Import failed, exception: 'ImportError'
2019-07-12 17:51:05.002 Error: (gBridge-Steinel) Error Line details not available.
2019-07-12 17:52:07.005 Error: gBridge-Steinel hardware (5) thread seems to have ended unexpectedly 
Any idea? The path is correct when I use a Terminal via ssh cd /home/pi/domoticz/plugins/domoticz-gbridge-plugin there is plugin.py. When open with sudo nano plugin.py its empty.

**Comment by giejay** [comment]
If its empty, then you probably didn't clone it correctly. Can you reclone?

**Comment by sailmich** [comment]
This morning code is in with sudo and without, but still same error

**Comment by giejay** [comment]
Can you do a chmod -R 666 on the folder?

**Comment by sailmich** [comment]
Do you mean folder domoticz-gbridge-plugin set to rw--rw--rw? Same error.

**Comment by giejay** [comment]
You are on master branch?

**Comment by sailmich** [comment]
Sorry what is a master branch?

**Comment by giejay** [comment]
How did you clone this repo? Or did you download the zip?

**Comment by sailmich** [comment]
As describe in gbridge documentation. Did git clone https://github.com/giejay/domoticz-gbridge-plugin.git in folder domoticz/plugins

**Comment by giejay** [comment]
That should be good, I'm kind of out of ideas

**Comment by sailmich** [comment]
Could it be a problem of Raspberry with python 3.4? https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/35

**Comment by giejay** [comment]
Ah yes, probably some features are used which are introduced in python 3.5. can you upgrade your python version?

**Comment by sailmich** [comment]
Seems to complicated for me. I don't want to mess my stable working domoticz. I tried it on my other Rpi and did something wrong. No I have a pyton 3.6 where I don't want it to have. If you can get me a step by step instruction I could try it.
Thank you very much for your support

**Comment by giejay** [comment]
Other then deinstalling 3.4 and doing a new install of 3, which should install 3.6, using apt-get, I dont really know how I can help you further. I also dont exactly know which of my code is not compatible with 3.4, I don't use any ** args as far as I can see. 

The best thing you can try is using docker. Then use compose or docker run domoticz and all should be fine.

**Comment by sailmich** [comment]
That's the point where I'm out :) Now I use another pizero as Domoticz remote server and try if gbridge work this way.
Thank you very much for your support
