### ISSUE TITLE
Receiving messages in the Domoticz log, but no update of the light

### ISSUE THREAD

**Issue by maartenaalbers** [giejay/domoticz-gbridge-plugin#20]
Hi,

This afternoon I took all steps to add the gBridge plugin to my Domoticz installation.
I now have everything configured, I added a light in the backoffice, configured Google assistant and I have the light added to a room in the Google Home App.
When I update the brightness, I see the following lines in my Domoticz log:

> 2019-11-06 19:33:34.532 (gBridge) Message from base
> 2019-11-06 19:33:34.532 (gBridge) Incoming message!{'Retain': False, 'QoS': 0, 'Topic': 'gBridge/u3432/d0/grequest', 'Verb': 'PUBLISH', 'Payload': b'EXECUTE', 'DUP': 0}
> 2019-11-06 19:33:34.533 (gBridge) MQTT message: gBridge/u3432/d0/grequest EXECUTE
> 2019-11-06 19:33:34.534 (gBridge) Message from base
> 2019-11-06 19:33:34.534 (gBridge) Incoming message!{'Retain': False, 'QoS': 0, 'Topic': 'gBridge/u3432/d11050/brightness', 'Verb': 'PUBLISH', 'Payload': b'65', 'DUP': 0}
> 2019-11-06 19:33:34.534 (gBridge) MQTT message: gBridge/u3432/d11050/brightness 65
> 2019-11-06 19:33:34.533 Error: (gBridge) 'onMessage' failed 'TypeError':'argument of type 'NoneType' is not iterable'.
> 2019-11-06 19:33:34.533 Error: (gBridge) ----> Line 208 in '/home/pi/domoticz/plugins/domoticz-gbridge-plugin/plugin.py', function onMessage
> 2019-11-06 19:33:34.533 Error: (gBridge) ----> Line 107 in '/home/pi/domoticz/plugins/domoticz-gbridge-plugin/plugin.py', function onMessage
> 2019-11-06 19:33:34.534 Error: (gBridge) ----> Line 126 in '/home/pi/domoticz/plugins/domoticz-gbridge-plugin/mqtt.py', function onMessage
> 2019-11-06 19:33:34.534 Error: (gBridge) ----> Line 164 in '/home/pi/domoticz/plugins/domoticz-gbridge-plugin/plugin.py', function onMQTTPublish
> 2019-11-06 19:33:34.534 Error: (gBridge) 'onMessage' failed 'TypeError':'argument of type 'NoneType' is not iterable'.
> 2019-11-06 19:33:34.534 Error: (gBridge) ----> Line 208 in '/home/pi/domoticz/plugins/domoticz-gbridge-plugin/plugin.py', function onMessage
> 2019-11-06 19:33:34.534 Error: (gBridge) ----> Line 107 in '/home/pi/domoticz/plugins/domoticz-gbridge-plugin/plugin.py', function onMessage
> 2019-11-06 19:33:34.535 Error: (gBridge) ----> Line 126 in '/home/pi/domoticz/plugins/domoticz-gbridge-plugin/mqtt.py', function onMessage
> 2019-11-06 19:33:34.535 Error: (gBridge) ----> Line 164 in '/home/pi/domoticz/plugins/domoticz-gbridge-plugin/plugin.py', function onMQTTPublish

But then... nothing happens. The light is not updated in Domoticz.

**Comment by giejay** [comment]
It seems like the domoticzDevices don't get populated. Can you share your logs when you restart the plug-in? Go to hardware, select your existing gBridge config and click update. Then go to the logs again.

**Comment by maartenaalbers** [comment]
This is the log:
<img width="912" alt="Screenshot 2019-11-06 at 20 42 15" src="https://user-images.githubusercontent.com/2944858/68331825-f368ff00-00d5-11ea-8f08-f1728e3e0971.png">

There is an a 401 error...

This is my config:
<img width="487" alt="Screenshot 2019-11-06 at 20 43 13" src="https://user-images.githubusercontent.com/2944858/68331982-3dea7b80-00d6-11ea-892a-29b46fd83c9c.png">
 
I'am able to get the devices list from `https://gbridge.kappelt.net/api/device` with the same credentials.

**Comment by giejay** [comment]
Did you follow step 3 in the readme:

Make sure you add "127.0.0.1" to your Local Networks under Settings.

**Comment by maartenaalbers** [comment]
That was indeed the issue, did a `,` instead of a `;` between the multiple ip's.
Moved to a Standard subscription, thanks for the good work!
