### ISSUE TITLE
Group Switch

### ISSUE THREAD

**Issue by Jochem22** [giejay/domoticz-gbridge-plugin#21]
I have created a Group Switch in domoticz under Scenes. I have added multiple switches to this group switch. The group switch is available at https://gbridge.kappelt.net/device as a scene. This wont show in my Google Home app. Are group switches supported?

**Comment by giejay** [comment]
Groups don't show up in Google Home afaik. Can you try saying 'turn on the {Group name}'?

**Comment by Jochem22** [comment]
> Groups don't show up in Google Home afaik. Can you try saying 'turn on the {Group name}'?

Ah thank you. This works! Only problem is that 'turn off the {Group name}' is not an option?

edit: I think i got it now. I have made scene which turn off all the lights. Activating this scene with "turn on the *scene name*" will actually turn off al the lights ;)

**Comment by giejay** [comment]
Yes, that depends on whether it's a scene or a group I guess. Scenes can only be turned on, if you put all the lights in a group, you can turn them on and off

**Comment by Jochem22** [comment]
> Yes, that depends on whether it's a scene or a group I guess. Scenes can only be turned on, if you put all the lights in a group, you can turn them on and off

I will test this tomorrow and let you know. Everything else works great, thank you for this great product.

**Comment by Jochem22** [comment]
You can actually see all the configured scenes/groups from gbridge in the Home App at: Settings > More settings > Assistant > Home control.

You can assign a room to the scene but it wont show up at the frontpage in Home App.

**Comment by Jochem22** [comment]
I cant get the group to turn on and off. I can only make it a scene and then command it trough google home. When i make it a group it will be seen as a scene by Google Home that i can only activate. I tried:

Hey google activate {group name}
Hey google deactivate {group name}
Hey google turn on {group name}
Hey google turn off {group name}

When i create a group and look at All Devices at https://gbridge.kappelt.net/device i can only see a scene without on/off function.

**Comment by giejay** [comment]
https://doc.gbridge.io/firstSteps/deviceTypes.html

Apparently groups are not supported, only scenes. But I think it would be more convenient to just create the group in Google Home app itself.
