### ISSUE TITLE
Can I use your code?

### ISSUE THREAD

**Issue by glsf91** [giejay/domoticz-gbridge-plugin#23]
I cannot send you a message so doing this way:

I'am thinking building a new domoticz plugin for using with another google home component using MQTT.
May I use your code as a base and adjust it?
I don't know yet if I going to publish this plugin. But just asking in case I will publish it in future.
Of course it will not be for commercial use.

**Comment by giejay** [comment]
Yes, feel free to use it!

**Comment by glsf91** [comment]
Thanks.
