### ISSUE TITLE
when saying lights of in room x, all devices are shut off

### ISSUE THREAD

**Issue by JurikRistjouw** [giejay/domoticz-gbridge-plugin#5]
before last commit, only the lights would turn of with the response, ok turning of 2 lights. Now somehow it turns of all devices in room x and responds ok, turning off 4 lights...  The switches have a switch icon and the lights have a light icon.

**Comment by giejay** [comment]
Can you try resyncing? Do you actually see 4 logs in the domoticz log regarding turning off of the devices? I have 13 devices, including 4 lights, when saying, turn off the lights, it only turns of the lights in the room I'm currently in.

The last commit doesn't change anything regarding switches/lights so that can't be it

**Comment by JurikRistjouw** [comment]
I see that all the devices are turning off, so the amount of devices is correct. But it only should turn on/off the lights, not also a fan and a heater. Tried resync (twice) but same results. Only thing that has changed was the last commit and therefor deleted the devices and readded. From then on this problem occurs.

**Comment by JurikRistjouw** [comment]
Maybe i should relink my google account and try again?

EDIT: just unlinked, deleted and readded and synced devices. now assigning rooms and will test further.

**Comment by JurikRistjouw** [comment]
update: I see what the problem is: on the newly linked list of devices in GH, i see the switches registering as a light! before it was a switch icon. so at this point, google sees 4 lights, instead of 2 lights and 2 switches. please advice

**Comment by giejay** [comment]
Switches are marked as lights based on whether the image in Domoticz is a light. I know, a bit tricky, but that was the only way for me to know whether a switch should be treated as a light. Does that apply for your switches?

**Comment by JurikRistjouw** [comment]
yes it does, in domoticz, it is registered as a fan and a heating device (was also the case when it did work)  the lights as a light.

**Comment by JurikRistjouw** [comment]
![image](https://user-images.githubusercontent.com/8580506/50378661-dc452e00-0637-11e9-8486-a88c5576ae3e.png)

these devices are in the Attic. The heating device is called "Attic heating" in gbridge friendly name, the other devices are named nearly as is

**Comment by giejay** [comment]
Can you share the json which is returned for this url: http://your-domoticz-ip:8080/json.htm?type=devices&filter=all&used=true&order=Name. Im specifically interested in the switches which are registered as lights.

**Comment by giejay** [comment]
I found the issue, and fixed it with latest (2) commits. Can you remove the devices from gBridge and try again?

**Comment by JurikRistjouw** [comment]
sure I will pull and reset all things.

For debug purposes, i've zipped my device result for you. when asked use your username as the word. 
[devices.zip](https://github.com/giejay/domoticz-gbridge-plugin/files/2705642/devices.zip)

**Comment by JurikRistjouw** [comment]
plugin disabled, pulled, deleted devices, synced devices twice
clean in GH now
restared domoticz
enabling plugin
readding devices in GH
testing.....

**Comment by JurikRistjouw** [comment]
YES it works! the returned numbers are not right but i guess that is cache. 

The lights are registering as lights and the others as switches. When asking google to turn off the lights, it does so and other devices stay on! "ok turning six lights on..."   I guess i have synced one time to many LOL

Cheers on you mate!

**Comment by giejay** [comment]
Awesome! Btw, for the next time, you don't need to stop Domoticz. You can do a git pull and click update for the gbridge hardware, thats enough to get the new codebase running.
