### ISSUE TITLE
gBridge and Domoticz on Raspberry pi 3?

### ISSUE THREAD

**Issue by JochemLangerak** [giejay/domoticz-gbridge-plugin#6]
Hi,

Is it possible to run both gBridge and Domoticz on a Raspberry Pi 3? And if yes, what would be the steps to get it up and running. I'm having a lot of issues getting gBridge to run on my pi. This really looks like the solution I prefer most (hosted myself, integrated with Domoticz), any help will be appreciated!

Best regards,

Jochem

**Comment by giejay** [comment]
Im also running it on a raspberry pi. Just follow the instructions on: https://doc.gbridge.io/selfHosted/hostItYourself.html and use the docker images from: https://github.com/kservices/gBridge-docker-arm32v6 in the docker compose file.

**Comment by JochemLangerak** [comment]
Seems like i'm getting closer. I've created the docker images (from the original location repo gbridge-docker). Everything is running now, but i've got some issues with the correct nginx configuration. 

I've tried to add       
      - PROXY_URL=https://gbridge.mydomain.nl:9443
      - PROXY_SCHEME=https

to environment: &webapp-environment in docker-compose.yml. But now every web call is changed. chrome is complaining about too many redirects and i cannot access to original login site anymore.

I've seen some posts where you mentioned to have it running already. Any tips would be nice!

Best regards,

Jochem

**Comment by giejay** [comment]
Can you share the rest of your docker compose file? Did you build the images yourself? Can you try the arm ones from the gBridge repo?

**Comment by giejay** [comment]
@JochemLangerak Do you still have issues with redirects?

**Comment by giejay** [comment]
Closed due to inactivity
