### ISSUE TITLE
Open close mapped wrong

### ISSUE THREAD

**Issue by christoferjh** [giejay/domoticz-gbridge-plugin#8]
Open close not sending correct switch command.

State: 100 should send command On

Log for door (open close) lock:

gBridge/uXXX/127/openclose/set, state: 100

2019-03-15 08:02:20.256 Status: User: Admin initiated a switch command (127/FrontLock/Off)

gBridge/uXXX/127/openclose/set, state: 0

2019-03-15 08:03:29.173 Status: User: Admin initiated a switch command (127/FrontLock/Off)

**Comment by christoferjh** [comment]
def handleMqttMessage(self, device, data, action, domoticz_port):
        if data == '1':
            command = 'On'
        else:
            command = 'Off'

Is it really that easy?

**Comment by christoferjh** [comment]
To invert would fix my problem

def handleMqttMessage(self, device, data, action, domoticz_port):
        if data == '0':
            command = 'Off'
        else:
            command = 'On'

**Comment by giejay** [comment]
I just made the change in develop. Can you try if this works for you? Thanks for the report!

**Comment by christoferjh** [comment]
Works great! Thanks!
