### ISSUE TITLE
No username and password with local MQTT

### ISSUE THREAD

**Issue by ArJay60** [giejay/domoticz-gbridge-plugin#9]
Working completely with a self hosted gBridge I don't want to use username and password on local Mosquitto instance. Hardware setup in Domoticz for the gBridge plugin requires MQTT username: and MQTT password can this be made optional?

**Comment by giejay** [comment]
You can just skip it right? Ah, never mind, I see the issue. I will make it optional.

**Comment by ArJay60** [comment]
Thxs

**Comment by SylvainPer** [comment]
Done in #10 if the PR is ok.

**Comment by giejay** [comment]
Yes, thank you Sylvain, its merged and available in develop branch.
